### ISSUE TITLE
Update coreLib desugaring

### ISSUE THREAD

**Issue by LikeTheSalad** [open-toast/gummy-bears#25]
Google's added support for `java.util.Base64` in its [latest corelib](https://github.com/google/desugar_jdk_libs/blob/HEAD/CHANGELOG.md#version-204-2023-11-01) version. However, it seems like gummy-bears-api-21 version `0.6.1` isn't aware of that change because it complains when it finds usages of `java.util.Base64` in the codebase.

**Comment by ogolberg** [comment]
This is on my radar, but I don't have a firm timeline for the upgrade.

As of 2.x, the desugaring libraries are structured a bit differently to support different flavors of desugaring (full, minimal, nio- see https://maven.google.com/web/index.html?q=desugar#com.android.tools:desugar_jdk_libs_configuration). Upgrading will require a nontrivial amount of work to parse the configuration from their jars to select the signatures that should be included in each flavor.

**Comment by LikeTheSalad** [comment]
I see, it does seem like it's gotten a lot more complicated for sure 😞 

I'm pretty sure that dealing with the fragmentation into multiple libs is going to be a lot of work, although in case it makes things a little easier, just wanted to mention that probably a "good-enough" option in the meantime could be addressing only the "full" library, which I guess should be the closest option to the 1.x lib before the fragmentation into multiple ones was carried out.

**Comment by ogolberg** [comment]
That's fair. Addressed in https://github.com/open-toast/gummy-bears/pull/26.

**Comment by ogolberg** [comment]
That's fair. Addressed in https://github.com/open-toast/gummy-bears/pull/26.
